const {assert,database,schedule,accounts,instructors,reports,history,notices,auth,request,call,signIn,seedAccount,entry,setSession}=require('./harness.cjs');
const {roomsForDate,canonicalRoom}=require('../availability.ts');
const {cancellationSelection,validDate}=require('../lib/cancellation-selection.ts');
const {reportDates,reportRows}=require('../lib/report.ts');
const results=[];
async function test(name,run){try{await run();results.push({name,passed:true})}catch(error){results.push({name,passed:false,error:error.message})}}
const getRequest=query=>({nextUrl:new URL('https://test.local/api'+query)});
const create=()=>({...entry('edge-thu',4),room:'QA-original'});
(async()=>{
 seedAccount('owner','admin');seedAccount('delegate','delegate');seedAccount('deputy','deputy');
 const password='qa-initial-password';database.prepare("UPDATE accounts SET password_hash=? WHERE id='owner'").run(await auth.hash(password));
 await test('anonymous protected APIs',async()=>{setSession('');assert.equal((await reports.GET(getRequest(''))).status,401);assert.equal((await history.GET(getRequest('?start=2026-10-08'))).status,401);assert.equal((await notices.GET(getRequest(''))).status,401);await call(accounts,{action:'save'},401)});
 await test('cross-origin mutations blocked',async()=>{for(const route of [accounts,schedule,instructors,notices]){const r=request({action:'login',username:'nawaf',password});r.headers.set('origin','https://evil.example');assert.equal((await route.POST(r)).status,403)}});
 await test('wrong password rejected',()=>call(accounts,{action:'login',username:'owner',password:'wrong'},401));
 await test('password login cookie and stored session',async()=>{const r=await accounts.POST(request({action:'login',username:'owner',password}));assert.equal(r.status,200);const c=r.cookieValues.saeed_session;assert.equal(c.options.httpOnly,true);assert.equal(c.options.secure,true);assert.equal(c.options.sameSite,'strict');assert.equal(c.options.maxAge,86400);assert.equal(database.prepare('SELECT COUNT(*) AS n FROM sessions WHERE token=?').get(await auth.digest(c.value)).n,1);setSession(c.value);assert.equal((await auth.account()).id,'owner')});
 await test('expired session rejected',async()=>{await signIn('owner');database.prepare('UPDATE sessions SET expires=0').run();assert.equal(await auth.account(),null)});
 await test('forged session rejected',async()=>{setSession('forged');assert.equal(await auth.account(),null)});
 await test('rate limit after ten failures',async()=>{setSession('');for(let i=0;i<10;i++)await call(accounts,{action:'login',username:'unknownuser',password:'wrong'},401);await call(accounts,{action:'login',username:'unknownuser',password:'wrong'},429)});
 await signIn('owner');await call(schedule,{action:'entry',entry:create()});
 await test('null account body rejected as client error',()=>call(accounts,null,400));
 await test('array account body rejected',()=>call(accounts,[],400));
 await test('missing username rejected',()=>call(accounts,{action:'save',name:'missing',password:'qa-password',role:'delegate',department:'SE',level:3},400));
 await test('missing status flag rejected',()=>call(accounts,{action:'status',id:'delegate'},400));
 await test('string permission rejected',()=>call(accounts,{action:'save',username:'stringflag',name:'test',password:'qa-password',role:'delegate',department:'SE',level:3,canEdit:'false'},400));
 await test('UI empty id creates account and instructor',async()=>{await call(accounts,{action:'save',id:'',username:'uicreate',name:'test',password:'qa-password',role:'delegate',department:'SE',level:3,canEdit:false});assert.equal(database.prepare("SELECT can_edit FROM accounts WHERE username='uicreate'").get().can_edit,0);await call(instructors,{id:'',name:'مدرس واجهة جديد',title:'م.'})});
 await test('duplicate usernames rejected',()=>call(accounts,{action:'save',username:'owner',name:'duplicate',password:'qa-password',role:'admin'},400));
 await test('unregistered teacher rejected',()=>call(accounts,{action:'save',username:'invalidteacher',name:'test',password:'qa-password',role:'teacher',instructorId:'missing',entryIds:['edge-thu']},400));
 await test('null instructor body rejected',async()=>{assert.equal((await instructors.POST(request(null))).status,400)});
 await test('null schedule body rejected',()=>call(schedule,null,400));
 await test('impossible semester date rejected',()=>call(schedule,{action:'setting',key:'termStart',value:'2026-02-30'},400));
 await test('valid leap-day semester date',()=>call(schedule,{action:'setting',key:'termStart',value:'2028-02-29'}));
 await test('invalid hour rejected',()=>call(schedule,{action:'entry',entry:{...create(),id:'invalid-hour',start:'24:00',end:'25:00'}},400));
 await test('invalid minute rejected',()=>call(schedule,{action:'entry',entry:{...create(),id:'invalid-minute',start:'08:60',end:'10:00'}},400));
 await test('unknown department rejected',()=>call(schedule,{action:'entry',entry:{...create(),id:'invalid-department',department:'UNKNOWN'}},400));
 await test('blank course rejected',()=>call(schedule,{action:'entry',entry:{...create(),id:'blank-course',course:'   '}},400));
 await test('wrong occurrence weekday rejected',()=>call(schedule,{action:'cancel',id:'edge-thu',date:'2026-10-07'},400));
 await test('nonexistent lecture rejected',()=>call(schedule,{action:'cancel',id:'missing',date:'2026-10-08'},404));
 await test('permanent cancellation rejected',()=>call(schedule,{action:'cancel',id:'edge-thu',date:'2026-10-08',scope:'weekly'},400));
 await test('unmatched batch selection rejected',()=>call(schedule,{action:'previewCancel',selection:{date:'2026-10-08',period:'day',department:'NOTFOUND'}},400));
 await test('room aliases share occupancy',async()=>{await call(schedule,{action:'entry',entry:{...create(),id:'room-occupant',room:'قاعة 9876'}});await call(schedule,{action:'location',id:'edge-thu',date:'2026-10-08',room:'9876'},409)});
 await test('cancelled lecture releases room for that date',async()=>{await call(schedule,{action:'cancel',id:'room-occupant',date:'2026-10-08'});await call(schedule,{action:'location',id:'edge-thu',date:'2026-10-08',room:'قاعة 9876'});await call(schedule,{action:'location',id:'edge-thu',date:'2026-10-15',room:'قاعة 9876'},409)});
 await test('adjacent time slots do not overlap',async()=>{await call(schedule,{action:'entry',entry:{...create(),id:'edge-adjacent',start:'10:00',end:'12:00'}});await call(schedule,{action:'location',id:'edge-adjacent',date:'2026-10-15',room:'قاعة 9876'})});
 await test('unchanged room remains valid',()=>call(schedule,{action:'location',id:'edge-thu',date:'2026-10-08',room:'قاعة 9876'}));
 await test('restoring original room cannot overwrite another booking',async()=>{await call(schedule,{action:'entry',entry:{...create(),id:'restore-a',room:'QA-restore-origin'}});await call(schedule,{action:'entry',entry:{...create(),id:'restore-b',room:'QA-restore-b'}});await call(schedule,{action:'location',id:'restore-a',date:'2026-10-08',room:'QA-restore-away'});await call(schedule,{action:'location',id:'restore-b',date:'2026-10-08',room:'QA-restore-origin'});await call(schedule,{action:'restoreLocation',id:'restore-a',date:'2026-10-08'},409)});
 await test('delegate cannot edit outside scope',async()=>{await signIn('delegate');await call(schedule,{action:'entry',entry:{...create(),id:'outside',department:'IT'}},403)});
 await test('deputy cannot cancel or read delegate notices',async()=>{await signIn('deputy');await call(schedule,{action:'cancel',id:'edge-thu',date:'2026-10-08'},403);assert.equal((await notices.GET(getRequest(''))).status,403)});
 await test('invalid notification offset rejected',async()=>{await signIn('delegate');assert.equal((await notices.GET(getRequest('?offset=-1'))).status,400);assert.equal((await notices.GET(getRequest('?offset=1.5'))).status,400)});
 await test('null notification body rejected',()=>call(notices,null,400));
 await test('malformed JSON rejected on every mutation API',async()=>{await signIn('owner');for(const route of [accounts,schedule,instructors]){const r=request({});r.json=async()=>{throw new SyntaxError('invalid JSON')};assert.equal((await route.POST(r)).status,400)}await signIn('delegate');const r=request({});r.json=async()=>{throw new SyntaxError('invalid JSON')};assert.equal((await notices.POST(r)).status,400)});
 await test('invalid audit dates and offsets rejected',async()=>{assert.equal((await history.GET(getRequest('?start=2026-02-30'))).status,400);assert.equal((await history.GET(getRequest('?start=2026-10-08&offset=-1'))).status,400)});
 await test('calendar leap days and year boundary',()=>{assert.equal(validDate('2026-02-29'),false);assert.equal(validDate('2028-02-29'),true);assert.deepEqual(reportDates('2026-12-31',2).map(x=>x.date),['2026-12-31','2027-01-01']);assert.deepEqual(reportDates('2026-02-30',7),[])});
 await test('week selection starts Saturday across year boundary',()=>{const list=cancellationSelection([entry('sat',6),entry('fri',5)],{date:'2027-01-01',period:'week'});assert.deepEqual(list.map(x=>x.date),['2026-12-26','2027-01-01'])});
 await test('numeric room alias normalization',()=>assert.equal(canonicalRoom('9876'),canonicalRoom('قاعة 9876')));
 await test('Arabic room spelling and Cisco aliases',()=>{assert.equal(canonicalRoom('قاعه 403'),canonicalRoom('قاعة 403'));assert.equal(canonicalRoom('ق 403'),canonicalRoom('403'));assert.equal(canonicalRoom('cisco'),canonicalRoom('قاعة سيسكو'))});
 await test('invalid availability date returns no rooms',()=>assert.deepEqual(roomsForDate([entry('x',1)],[],'2026-02-30','08:00','10:00'),[]));
 await test('report occurrence isolation',()=>{const rows=reportRows([entry('x',4)],[{entryId:'x',date:'2026-10-08',reason:'test'}],[],'2026-10-08',8);assert.equal(rows.length,2);assert.equal(rows[0].cancelled,true);assert.equal(rows[1].cancelled,false)});
 await test('password change revokes all sessions',async()=>{await signIn('owner');await call(accounts,{action:'password',current:password,password:'qa-new-password'});assert.equal(await auth.account(),null);await call(accounts,{action:'login',username:'owner',password},401);await call(accounts,{action:'login',username:'owner',password:'qa-new-password'})});
 await test('logout invalidates session',async()=>{await signIn('owner');await call(accounts,{action:'logout'});assert.equal(await auth.account(),null)});
 for(const result of results)console.log(`${result.passed?'PASS':'FAIL'}: ${result.name}${result.error?' — '+result.error:''}`);
 const failed=results.filter(x=>!x.passed);console.log(`RESULT: ${results.length-failed.length}/${results.length} edge cases passed`);if(failed.length)process.exitCode=1;
})().catch(error=>{console.error(error);process.exitCode=1});
