'use client';
import {NotificationsPanel} from '../components/notifications-panel';
import { ScheduleReports } from '../components/schedule-reports';
import {TeachingPanel} from '../components/teaching-panel';
import { AccountPanel } from '../components/account-panel';
import { useEffect, useMemo, useState } from 'react';
import { Search, SlidersHorizontal, CalendarDays, Plus, X, Pencil, Trash2, Shield, BookOpen, MapPin, UserRound } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { seed, days, departments, type Entry } from '../data';
import { roomsForDate, isCancelledOnDate, weeklyCancellationFor, type Cancellation } from '../availability';

type Payload={id?:string;isOwner?:boolean;assignedEntryIds?:string[];instructors?:any[];name?:string;department?:string;level?:number;locations:{entryId:string;date:string;room:string;reason:string}[];entries:Entry[];cancellations:Cancellation[];settings:Record<string,string>;members:{email:string;role:string;canEdit:number}[];role:string;email:string;canEdit:boolean;canCancel:boolean;verifiedCount:number};
const base:Payload={entries:seed,locations:[],cancellations:[],settings:{},members:[],role:'viewer',email:'',canEdit:false,canCancel:false,verifiedCount:seed.length};
const unique=(a:string[])=>[...new Set(a.filter(Boolean))].sort((x,y)=>x.localeCompare(y,'ar'));
const searchable=(s:unknown)=>String(s??'').toLocaleLowerCase('ar').replace(/\s+/g,'').replace(/[أإآ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه');
const dt=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const dateFor=(day:number,start:string)=>{const anchor=new Date(`${start}T12:00:00`);if(Number.isNaN(+anchor))return '';const now=new Date();const a=now>anchor?new Date(now):anchor;a.setHours(12,0,0,0);a.setDate(a.getDate()+(day-a.getDay()+7)%7);return new Intl.DateTimeFormat('ar-YE',{day:'numeric',month:'long',year:'numeric'}).format(a)};
const nextDate=(day:number)=>{const now=new Date();now.setDate(now.getDate()+(day-now.getDay()+7)%7);return dt(now)};
const blank=():Entry=>({id:'',day:6,department:'IT',level:1,start:'08:00',end:'10:00',course:'',instructor:'',room:'',groupName:'',kind:'محاضرة',source:''});
function Picker({value,onChange,choices,all}:{value:string;onChange:(x:string)=>void;choices:string[];all:string}){return <Select value={value||'_all'} onValueChange={v=>onChange(v==='_all'?'':v)}><SelectTrigger className="filter"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="_all">{all}</SelectItem>{choices.map(x=><SelectItem key={x} value={/^\d+:/.test(x)?x.split(':')[0]:x}>{/^\d+:/.test(x)?x.split(':')[1]:x}</SelectItem>)}</SelectContent></Select>}
export default function Home({adminPage=false}:{adminPage?:boolean}){
 const [locationTarget,setLocationTarget]=useState<{entry:Entry;date:string}|null>(null),[newRoom,setNewRoom]=useState(''),[locationReason,setLocationReason]=useState('');
 const [data,setData]=useState(base),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[level,setLevel]=useState(''),[department,setDepartment]=useState(''),[teacher,setTeacher]=useState(''),[room,setRoom]=useState(''),[day,setDay]=useState('next'),[edit,setEdit]=useState<Entry|null>(null),[open,setOpen]=useState(false),[panel,setPanel]=useState(false),[term,setTerm]=useState(''),[invite,setInvite]=useState(''),[inviteRole,setInviteRole]=useState('delegate'),[inviteCanEdit,setInviteCanEdit]=useState(false),[saving,setSaving]=useState(false),[selectedDate,setSelectedDate]=useState(''),[availabilityStart,setAvailabilityStart]=useState('08:00'),[availabilityEnd,setAvailabilityEnd]=useState('10:00'),[cancelTarget,setCancelTarget]=useState<{entry:Entry;date:string}|null>(null),[cancelReason,setCancelReason]=useState(''),[cancelScope,setCancelScope]=useState<'date'|'weekly'>('date'),[showAllRooms,setShowAllRooms]=useState(false),[clock,setClock]=useState<Date|null>(null);
 const refresh=async()=>{try{const r=await fetch('/api/schedule',{cache:'no-store'});if(!r.ok)throw Error();const d=await r.json() as Payload;setData(d);setTerm(d.settings.termStart||'');setError('')}catch{setError('تعذر التحقق من الحساب وتحميل الجدول. أعد تحميل الصفحة.');throw Error('تعذر التحقق من الحساب. أعد المحاولة.')}finally{setLoading(false)}};
 useEffect(()=>{refresh().catch(()=>{});setClock(new Date())},[]);
 const upcoming=clock?Array.from({length:14},(_,i)=>{const x=new Date(clock);x.setDate(clock.getDate()+i);return x}).filter(x=>x.getDay()!==5 && data.entries.some(e=>Number(e.day)===x.getDay())).slice(0,2):[];
 const availabilityDate=selectedDate||(clock?(day==='next'?(upcoming[0]?dt(upcoming[0]):dt(clock)):(()=>{const d=new Date(clock);d.setDate(d.getDate()+(Number(day)-d.getDay()+7)%7);return dt(d)})()):'');
 const changeDate=(value:string)=>{setSelectedDate(value);if(value)setDay(String(new Date(`${value}T12:00:00`).getDay()))};
 const selectedDays=selectedDate?[new Date(`${selectedDate}T12:00:00`).getDay()]:day==='next'&&query.trim()?[6,0,1,2,3,4]:day==='next'?upcoming.map(x=>x.getDay()):[Number(day)];
 const entries=useMemo(()=>data.entries.filter(e=> selectedDays.includes(Number(e.day)) &&(!level||String(e.level)===level)&&(!department||e.department===department)&&(!teacher||searchable(e.instructor).includes(searchable(teacher)))&&(!room||e.room===room)&&(!query||[e.course,e.instructor,e.room,e.department,e.groupName].some(s=>searchable(s).includes(searchable(query.trim()))))).sort((a,b)=>Number(a.day)-Number(b.day)||a.start.localeCompare(b.start)||a.department.localeCompare(b.department)),[data.entries,selectedDate,day,level,department,teacher,room,query,clock]);
 const effectiveEntries=(date:string)=>data.entries.map(e=>({...e,room:data.locations.find(l=>l.entryId===e.id&&l.date===date)?.room||e.room}));
 const inScope=(e:Entry)=>data.role==='admin'||(data.role==='teacher'?(data.assignedEntryIds||[]).includes(e.id):(data.department===e.department&&data.level===Number(e.level)));
 const rooms=roomsForDate([...effectiveEntries(availabilityDate),...data.entries.map(e=>({...e,day:-1}))],data.cancellations,availabilityDate,availabilityStart,availabilityEnd);const freeRooms=rooms.filter(r=>r.occupants.length===0);
 const allTeachers=unique(data.entries.map(x=>x.instructor));const allRooms=unique(data.entries.map(x=>x.room));const canEdit=data.canEdit;const canCancel=data.canCancel;
 const send=async(body:unknown)=>{setSaving(true);setError('');try{const r=await fetch('/api/schedule',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const res=await r.json() as {error?:string};if(!r.ok)throw Error(res.error||'تعذر الحفظ');await refresh();return true}catch(e){setError(e instanceof Error?e.message:'تعذر الحفظ');return false}finally{setSaving(false)}};
 const saveEntry=async(e:Entry)=>{if(await send({action:'entry',entry:e})){setOpen(false);setEdit(null)}};
 const clear=()=>{setQuery('');setLevel('');setDepartment('');setTeacher('');setRoom('');setDay('next');setSelectedDate('')};
 return <main className="site" dir="rtl"><header className="top"><div className="brand"><img className="universityLogo" src="/taiz-university-logo.jpg" alt="شعار جامعة تعز" width="50" height="57"/><div><strong>كلية السعيد</strong><small>جامعة تعز · الجدول الدراسي ٢٠٢٦–٢٠٢٧</small></div></div><div className="topActions">{!data.email&&<a className="adminLink" href="/login">تسجيل الدخول</a>}{data.role==='delegate'&&<a className="roomLink" href="#notifications">الإشعارات</a>}<a className="roomLink" href="#reports">التقارير</a><a className="roomLink" href="#cancelled">محاضرات ملغية</a><a className="roomLink" href="#rooms">القاعات المتاحة</a>{canEdit&&<Button className="primary" onClick={()=>{setEdit({...blank(),department:data.department||'SE',level:data.level||1});setOpen(true)}}><Plus size={17}/> إضافة موعد</Button>}{data.role==='admin'&&<a className="adminLink" href={adminPage?'/':'/admin'}><Shield size={16}/>{adminPage?'الجدول العام':'الإدارة'}</a>}</div></header>
 {adminPage&&data.role==='admin'&&<section className="adminPage" aria-labelledby="admin-title"><div className="adminHeading"><div><h1 id="admin-title">لوحة الإدارة</h1><p>{loading?'جارٍ التحقق من الحساب والصلاحيات…':data.role==='admin'?`${data.name||''} · ${data.isOwner?'الحساب الرئيسي':'مدير'} · إدارة الكلية`:data.email?'إدارة حسابك ومحاضرات دفعتك':'سجل الدخول لعرض أدوات الإدارة'}</p></div>{canCancel&&<a href="#schedule">إدارة المحاضرات وإلغاؤها</a>}</div><div className="adminBody"><AccountPanel data={data} refresh={refresh}/><p>صلاحيتك: <b>{data.role==='admin'?'مسؤول':data.role==='delegate'?'مندوب/مندوبة':data.role==='deputy'?'نائب المندوب':'عرض فقط'}</b>{data.email?` · ${data.email}`:''}</p>{data.role==='admin'&&<><div className="adminBlock"><h3>بداية الفصل</h3><p>حدد تاريخ البداية مرة واحدة؛ يظهر تاريخ اليوم المختار تلقائيًا ويتكرر الجدول كل أسبوع.</p><div className="inline"><input type="date" value={term} onChange={e=>setTerm(e.target.value)}/><Button disabled={saving||!term} onClick={()=>send({action:'setting',key:'termStart',value:term})}>حفظ التاريخ</Button></div></div></>}{canEdit&&<p className="note"><BookOpen size={16}/> أضف أي موعد غير موجود من زر «إضافة موعد». تُحفظ الإضافات والتعديلات لجميع أعضاء الفريق.</p>}{error&&<p className="failure">{error}</p>}</div></section>}
 {!adminPage&&data.role==='admin'&&<div className="ownerNotice">{data.name} · {data.isOwner?'الحساب الرئيسي':'مدير'} · صلاحيات الإدارة مفعّلة</div>}
 {!loading&&!data.email&&!adminPage&&<div className="ownerNotice">لإلغاء المحاضرات أو تغيير أماكنها، <a href="/login">سجل الدخول</a>.</div>}
 {!adminPage&&data.email&&data.role!=='admin'&&<details className="adminPage"><summary>حسابي</summary><AccountPanel data={data} refresh={refresh}/></details>}
 {data.role==='delegate'&&<NotificationsPanel onDateChange={changeDate}/>}
 {data.role==='teacher'&&<TeachingPanel data={data} refresh={refresh}/>}
 <ScheduleReports start={availabilityDate} onDateChange={changeDate} authenticated={!!data.email} entries={data.entries} cancellations={data.cancellations} locations={data.locations} loading={loading} error={error}/>
 <section className="intro"><div><div className="eyebrow"><CalendarDays size={17}/> الفصل الأول · ٢٠٢٦–٢٠٢٧</div><h1>جدول المحاضرات</h1><p>ابحث عن موعدك بحسب المقرر أو المدرس أو القاعة.</p></div><div className="introBadge"><span>الأيام المعروضة</span><b>{selectedDate?days[new Date(`${selectedDate}T12:00:00`).getDay()]:day==='next'?'اليومان القادمان':days[Number(day)]}</b><small>{selectedDate?selectedDate:day==='next'?upcoming.map(x=>`${days[x.getDay()]} ${new Intl.DateTimeFormat('ar-YE',{day:'numeric',month:'short'}).format(x)}`).join(' · '):term?dateFor(Number(day),term):'يتكرر الموعد أسبوعيًا'}</small></div></section>
 <section className="controls"><div className="searchbox"><Search size={21}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث عن مقرر، مدرس، أو قاعة" aria-label="بحث في الجدول"/></div><div className="filterRow"><div className="filterLabel"><SlidersHorizontal size={17}/> تصفية</div><Picker value={level} onChange={setLevel} choices={['1','2','3','4','5']} all="كل المستويات"/><Picker value={department} onChange={setDepartment} choices={unique([...departments,...data.entries.map(e=>e.department)])} all="كل الأقسام"/><input className="teacherFilter" value={teacher} onChange={e=>setTeacher(e.target.value)} placeholder="اسم الدكتور" list="teacher-options" aria-label="تصفية حسب الدكتور"/><datalist id="teacher-options">{allTeachers.map(x=><option key={x} value={x}/>)}</datalist><Picker value={room} onChange={setRoom} choices={allRooms} all="كل القاعات"/><Picker value={day} onChange={setDay} choices={days.map((x,i)=>`${i}:${x}`)} all="اليومان القادمان"/><button className="reset" onClick={clear}>مسح الفلاتر</button></div><div className="dateSelect"><label>تاريخ آخر (اختياري)<input type="date" value={availabilityDate} onChange={e=>changeDate(e.target.value)}/></label>{selectedDate&&<button onClick={()=>setSelectedDate('')}>العودة للجدول الأسبوعي</button>}</div><div className="daystrip"><button className={day==='next'&&!selectedDate?'active':''} onClick={()=>{setDay('next');setSelectedDate('')}}>اليومان القادمان</button>{[6,0,1,2,3,4].map(n=><button key={n} className={day===String(n)&&!selectedDate?'active':''} onClick={()=>{setDay(String(n));setSelectedDate('')}}>{days[n]}</button>)}</div></section>
 <section className="results" id="schedule"><div className="resultHead"><h2>المواعيد <span>{entries.length}</span></h2><small>{loading?'جارِ التحميل…':error||'السجل الأسبوعي يتكرر تلقائيًا في الأسابيع القادمة'}</small></div>{selectedDays.map(n=>{const list=entries.filter(e=>Number(e.day)===n);return <div className="dayGroup" key={n}><div className="dayHeading"><h3>{days[n]}</h3><span>{list.length} موعد</span></div>{list.length?<div className="cards">{list.map(e=>{const occurrence=selectedDate||upcoming.find(d=>d.getDay()===Number(e.day))&&dt(upcoming.find(d=>d.getDay()===Number(e.day))!)||nextDate(Number(e.day));const weeklyCancel=weeklyCancellationFor(data.cancellations,e.id,occurrence);const isCancelled=isCancelledOnDate(data.cancellations,e.id,occurrence);return <article className={`card ${isCancelled?'cancelled':''}`} key={e.id}><div className="cardTop"><span className="time" dir="ltr">{e.start} — {e.end}</span><span className="kind">{isCancelled?('ملغى في '+occurrence):e.kind}</span></div><h4>{e.course}</h4><div className="details"><span><MapPin size={15}/>{data.locations.find(l=>l.entryId===e.id&&l.date===occurrence)?.room||e.room}{data.locations.some(l=>l.entryId===e.id&&l.date===occurrence)&&<small> (تغيير لهذا الموعد)</small>}</span><span><UserRound size={15}/>{e.instructor}</span></div><div className="cardFoot"><span>{e.department} · المستوى {e.level}{e.groupName?` · ${e.groupName}`:''}</span>{inScope(e)&&(canEdit||canCancel)&&<span className="actions">{canCancel&&<button className="cancelAction" onClick={()=>{setCancelTarget({entry:e,date:occurrence});setCancelReason('');setCancelScope('date')}}>{isCancelled?'استعادة المحاضرة':'إلغاء المحاضرة'}</button>}{canCancel&&data.role!=='teacher'&&<button className="cancelAction" onClick={()=>{setLocationTarget({entry:e,date:occurrence});setNewRoom(data.locations.find(l=>l.entryId===e.id&&l.date===occurrence)?.room||e.room);setLocationReason('')}}>تغيير المكان</button>}{canEdit&&<button aria-label="تعديل" onClick={()=>{setEdit({...e});setOpen(true)}}><Pencil size={16}/></button>}{canEdit&&<button aria-label="حذف الموعد الأسبوعي" title="حذف الموعد من كل الأسابيع" onClick={()=>{if(confirm('سيُحذف الموعد من جميع الأسابيع، وليس من يوم واحد فقط. هل تريد المتابعة؟'))send({action:'delete',id:e.id})}}><Trash2 size={16}/></button>}</span>}</div></article>})}</div>:<div className="empty">لا توجد مواعيد مدخلة لهذا اليوم بهذه الفلاتر.</div>}</div>})}</section>
 <section className="roomsSection" id="rooms"><section className="availability"><div className="availabilityHead"><div><h2>القاعات دون حجز مسجل</h2><p>يظهر التاريخ تلقائيًا؛ يمكنك تغييره عند الحاجة. تُحسب الحجوزات من جميع الأقسام، ويُستثنى ما أُلغي لهذا التاريخ فقط.</p></div><strong>{availabilityStart<availabilityEnd?freeRooms.length:0} قاعة متاحة</strong></div><div className="availabilityControls"><label>التاريخ<input type="date" value={availabilityDate} onChange={e=>changeDate(e.target.value)}/></label><label>من<select value={availabilityStart} onChange={e=>setAvailabilityStart(e.target.value)}>{['08:00','09:00','10:00','11:00','12:00','13:00','14:00','15:00'].map(t=><option key={t} value={t}>{t}</option>)}</select></label><label>إلى<select value={availabilityEnd} onChange={e=>setAvailabilityEnd(e.target.value)}>{['09:00','10:00','11:00','12:00','13:00','14:00','15:00','16:00'].map(t=><option key={t} value={t}>{t}</option>)}</select></label><Button variant="outline" onClick={()=>changeDate(availabilityDate)}>عرض مواعيد هذا التاريخ</Button></div>{availabilityStart>=availabilityEnd?<div className="empty">وقت النهاية يجب أن يكون بعد البداية.</div>:<div className="roomList">{freeRooms.length?(showAllRooms?freeRooms:freeRooms.slice(0,8)).map(r=><span className="roomChip" key={r.name}><MapPin size={14}/>{r.name}</span>):<span className="noRooms">لا توجد قاعات متاحة مسجلة في هذه الفترة.</span>}</div>}{freeRooms.length>8&&availabilityStart<availabilityEnd&&<button className="roomsToggle" onClick={()=>setShowAllRooms(v=>!v)}>{showAllRooms?'عرض أقل':`عرض جميع القاعات (${freeRooms.length})`}</button>}<small className="availabilityNote">تعتمد النتيجة على الحجوزات المدخلة فقط. القاعات غير المحددة والمواعيد غير المدخلة لا تُحتسب.</small></section></section>
 <section className="roomsSection" id="cancelled"><div className="availability"><h2>محاضرات ملغية</h2><p>إلغاء موعد واحد فقط؛ يبقى موعد الأسبوع التالي قائمًا.</p>{data.cancellations.length?data.cancellations.slice().sort((a,b)=>b.date.localeCompare(a.date)).map((c,i)=>{const e=data.entries.find(e=>e.id===c.entryId);return <div className="member" key={c.entryId+c.date+i}><div><strong>{e?.course||'محاضرة محذوفة'}</strong><small>{c.date} · {e?.department} · المستوى {e?.level} · {c.reason||'بدون سبب مسجل'}</small></div>{e&&canCancel&&inScope(e)&&<button disabled={saving} onClick={()=>send({action:'restore',id:e.id,date:c.date})}>استعادة الموعد</button>}</div>}):<p>لا توجد محاضرات ملغية.</p>}</div></section>
 <Dialog open={!!locationTarget} onOpenChange={v=>{if(!v)setLocationTarget(null)}}><DialogContent className="editor" dir="rtl"><DialogHeader><DialogTitle>تغيير مكان المحاضرة</DialogTitle></DialogHeader>{locationTarget&&<form className="cancelForm" onSubmit={async e=>{e.preventDefault();if(await send({action:'location',id:locationTarget.entry.id,date:locationTarget.date,room:newRoom,reason:locationReason}))setLocationTarget(null)}}><p>{locationTarget.entry.course} · {locationTarget.date}</p><p>التغيير لهذا الموعد فقط؛ يعود المكان الأصلي في الأسبوع التالي.</p><label>القاعة أو المعمل أو الورشة<input required list="room-options" value={newRoom} onChange={e=>setNewRoom(e.target.value)}/><datalist id="room-options">{allRooms.map(r=><option key={r} value={r}/>)}</datalist></label><label>سبب التغيير<input value={locationReason} onChange={e=>setLocationReason(e.target.value)}/></label><Button disabled={saving} type="submit">حفظ المكان</Button><Button type="button" disabled={saving} variant="outline" onClick={async()=>{if(await send({action:'restoreLocation',id:locationTarget.entry.id,date:locationTarget.date}))setLocationTarget(null)}}>استعادة المكان الأصلي</Button>{error&&<p role="alert" className="failure">{error}</p>}</form>}</DialogContent></Dialog>
 <footer><span>المواعيد المستخرجة من ملفات الجدول: {data.verifiedCount}. يمكن للفريق تصحيح البيانات وإضافة أي موعد غير وارد في الملفات.</span><span className="developerCredit">تطوير: نواف محمد علي همام</span></footer>
 <Dialog open={!!cancelTarget} onOpenChange={v=>{if(!v)setCancelTarget(null)}}><DialogContent className="editor" dir="rtl"><DialogHeader><DialogTitle>إدارة إلغاء المحاضرة</DialogTitle></DialogHeader>{cancelTarget&&<div className="cancelForm">{error&&<p role="alert" className="failure">{error}</p>}<p><b>{cancelTarget.entry.course}</b> · {cancelTarget.entry.room}</p><p>{days[cancelTarget.entry.day]} · {cancelTarget.date} · <span dir="ltr">{cancelTarget.entry.start}–{cancelTarget.entry.end}</span></p><p>الإلغاء لهذا الموعد فقط. تعود المحاضرة تلقائيًا في الأسبوع التالي.</p>{!(cancelScope==='weekly'?weeklyCancellationFor(data.cancellations,cancelTarget.entry.id,cancelTarget.date):data.cancellations.some(c=>c.entryId===cancelTarget.entry.id&&c.date===cancelTarget.date))&&<label>سبب الإلغاء (اختياري)<Input value={cancelReason} onChange={e=>setCancelReason(e.target.value)} placeholder="مثلاً: تغيير موعد المحاضرة"/></label>}<Button className="primary" disabled={saving} onClick={async()=>{const wasCancelled=cancelScope==='weekly'?!!weeklyCancellationFor(data.cancellations,cancelTarget.entry.id,cancelTarget.date):data.cancellations.some(c=>c.entryId===cancelTarget.entry.id&&c.date===cancelTarget.date);if(await send({action:wasCancelled?'restore':'cancel',id:cancelTarget.entry.id,date:cancelTarget.date,scope:cancelScope,reason:cancelReason})){changeDate(cancelTarget.date);setCancelTarget(null)}}}>{(cancelScope==='weekly'?!!weeklyCancellationFor(data.cancellations,cancelTarget.entry.id,cancelTarget.date):data.cancellations.some(c=>c.entryId===cancelTarget.entry.id&&c.date===cancelTarget.date))?'استعادة '+(cancelScope==='weekly'?'كل الأسابيع التالية':'هذا التاريخ'):'تأكيد الإلغاء '+(cancelScope==='weekly'?'لكل الأسابيع التالية':'لهذا التاريخ')}</Button></div>}</DialogContent></Dialog>
 <Dialog open={open} onOpenChange={setOpen}><DialogContent className="editor" dir="rtl"><DialogHeader><DialogTitle>{edit?.id?'تعديل موعد':'إضافة موعد'}</DialogTitle></DialogHeader>{edit&&<form onSubmit={e=>{e.preventDefault();saveEntry(edit)}}><div className="formGrid"><label>اليوم<select value={edit.day} onChange={e=>setEdit({...edit,day:Number(e.target.value)})}>{[6,0,1,2,3,4].map(n=><option key={n} value={n}>{days[n]}</option>)}</select></label><label>القسم<select value={edit.department} onChange={e=>setEdit({...edit,department:e.target.value})}>{unique([...departments,...data.entries.map(x=>x.department)]).map(x=><option key={x}>{x}</option>)}</select></label><label>المستوى<select value={edit.level} onChange={e=>setEdit({...edit,level:Number(e.target.value)})}>{[1,2,3,4,5].map(x=><option key={x}>{x}</option>)}</select></label><label>النوع<select value={edit.kind} onChange={e=>setEdit({...edit,kind:e.target.value})}>{unique(['محاضرة',...seed.map(x=>x.kind),edit.kind]).map(x=><option key={x}>{x}</option>)}</select></label><label>من<input required type="time" value={edit.start} onChange={e=>setEdit({...edit,start:e.target.value})}/></label><label>إلى<input required type="time" value={edit.end} onChange={e=>setEdit({...edit,end:e.target.value})}/></label><label className="wide">المقرر<input required value={edit.course} onChange={e=>setEdit({...edit,course:e.target.value})}/></label><label>الدكتور أو المدرس<input list="registered-instructors" required value={edit.instructor} onChange={e=>setEdit({...edit,instructor:e.target.value})}/></label><datalist id="registered-instructors">{(data.instructors||[]).map(p=><option key={p.id} value={[p.title,p.name].filter(Boolean).join(" ")}/>)}</datalist><label>القاعة أو المعمل<input required value={edit.room} onChange={e=>setEdit({...edit,room:e.target.value})}/></label><label className="wide">المجموعة، إن وجدت<input value={edit.groupName} onChange={e=>setEdit({...edit,groupName:e.target.value})}/></label></div><Button className="primary save" type="submit" disabled={saving}>حفظ الموعد</Button></form>}</DialogContent></Dialog>

 </main>
}
