'use client';
import type {SchedulePayload} from '../lib/payload';
import {useMemo,useState,useRef} from 'react';
import {useRouter} from 'next/navigation';
import {departments} from '../data';
import {teachingGroups,instructorLabel,instructorParts,type Instructor} from '../lib/teaching';
const empty={id:'',username:'',name:'',password:'',department:'SE',level:3,role:'delegate',canEdit:false,instructorId:'',entryIds:[] as string[]};
const roleName=(role:string)=>({admin:'مدير',teacher:'مدرس مقرر',delegate:'مندوب',deputy:'نائب المندوب'}[role]||role);
export function AccountPanel({data,refresh}:{data:SchedulePayload;refresh:()=>Promise<void>}){
 const router=useRouter();
 const [form,setForm]=useState(empty),[profile,setProfile]=useState({id:'',name:'',title:''}),[query,setQuery]=useState(''),[password,setPassword]=useState({current:'',password:''}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const accountForm=useRef<HTMLFormElement>(null),instructorForm=useRef<HTMLFormElement>(null);
 const navigateTo=(target:{current:HTMLFormElement|null})=>requestAnimationFrame(()=>{target.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});target.current?.querySelector<HTMLInputElement>('input')?.focus({preventScroll:true})});
 const instructors:Instructor[]=data.instructors||[];
 const groups=useMemo(()=>teachingGroups(data.entries||[]),[data.entries]);
 const titles=[...new Set(['د.','م.','أ.','أ. د.','مدرس',...instructors.map(p=>p.title)].filter(Boolean))];
 const send=async(body:unknown,url='/api/account')=>{setBusy(true);setMessage('');try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'تعذر الحفظ');await refresh();setMessage('تم الحفظ');return true}catch(e){setMessage((e as Error).message);return false}finally{setBusy(false)}};
 const chooseInstructor=(id:string)=>{const p=instructors.find(p=>p.id===id);setForm({...form,instructorId:id,name:p?instructorLabel(p):'',entryIds:groups.filter(g=>p&&instructorParts(g.instructor).includes(instructorLabel(p))).flatMap(g=>g.entries.map(e=>e.id))})};
 const toggleGroup=(ids:string[],checked:boolean)=>setForm({...form,entryIds:checked?[...new Set([...form.entryIds,...ids])]:form.entryIds.filter(id=>!ids.includes(id))});
 return <div className="accountPanel">
 {data.email&&<><p><b>{data.name}</b> · {data.isOwner?'الحساب الرئيسي':roleName(data.role)}</p><button disabled={busy} onClick={async()=>{if(await send({action:'logout'})){router.push('/');router.refresh()}}}>تسجيل الخروج</button>
 <form className="memberForm adminBlock" onSubmit={async e=>{e.preventDefault();if(await send({action:'password',...password})){setPassword({current:'',password:''});router.push('/login');router.refresh()}}}><h3>تغيير كلمة المرور</h3><label>كلمة المرور الحالية<input required type="password" autoComplete="current-password" value={password.current} onChange={e=>setPassword({...password,current:e.target.value})}/></label><label>كلمة المرور الجديدة<input required minLength={6} maxLength={128} type="password" autoComplete="new-password" value={password.password} onChange={e=>setPassword({...password,password:e.target.value})}/></label><button className="primary" disabled={busy}>حفظ كلمة المرور</button></form></>}
 {data.role==='admin'&&<>
 <section className="adminBlock" id="instructor-management"><h3>سجل المدرسين</h3><p>الاسم واللقب العلمي كما يظهران في الجدول. تعديلهما يحدّث عرض المحاضرات المرتبطة بالمدرس.</p>
 <form ref={instructorForm} id="instructor-form" className="memberForm" onSubmit={async e=>{e.preventDefault();if(await send(profile,'/api/instructors'))setProfile({id:'',name:'',title:''})}}><label>اسم المدرس<input required maxLength={120} value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label>اللقب أو الدرجة العلمية<input list="academic-titles" maxLength={40} value={profile.title} onChange={e=>setProfile({...profile,title:e.target.value})} placeholder="د. أو م. أو أ."/><datalist id="academic-titles">{titles.map(t=><option key={t} value={t}/>)}</datalist></label><button className="primary" disabled={busy}>{profile.id?'حفظ بيانات المدرس':'إضافة مدرس'}</button>{profile.id&&<button type="button" onClick={()=>setProfile({id:'',name:'',title:''})}>إلغاء التعديل</button>}</form>
 <details className="teacherRegistry"><summary>المدرسون ({instructors.length})</summary>{instructors.map(p=><div className="member" key={p.id}><strong>{instructorLabel(p)}</strong><div className="memberActions"><button disabled={busy} onClick={()=>{setProfile({id:p.id,name:p.name,title:p.title});navigateTo(instructorForm)}}>تعديل البيانات</button><button disabled={busy} onClick={()=>{const ids=groups.filter(g=>instructorParts(g.instructor).includes(instructorLabel(p))).flatMap(g=>g.entries.map(e=>e.id));setQuery('');setForm({...empty,role:'teacher',instructorId:p.id,name:instructorLabel(p),entryIds:ids});navigateTo(accountForm)}}>إنشاء حساب</button></div></div>)}</details></section>
 <section className="adminBlock"><h3>الحسابات والصلاحيات</h3><p>المدرس يدير إلغاء المحاضرات المحددة له فقط. إنشاء المديرين وإدارة حساباتهم للحساب الرئيسي وحده.</p>
 <form ref={accountForm} id="account-form" className="memberForm" onSubmit={async e=>{e.preventDefault();if(await send({action:'save',...form}))setForm(empty)}}>
 <h3 className="accountWide">{form.id?'تعديل بيانات الحساب':'إنشاء حساب جديد'}</h3>
 <label>الدور<select value={form.role} onChange={e=>setForm({...form,role:e.target.value,canEdit:false})}><option value="delegate">مندوب</option><option value="deputy">نائب المندوب</option><option value="teacher">مدرس مقرر</option>{data.isOwner&&<option value="admin">مدير</option>}</select></label>
 {form.role==='teacher'&&<label>المدرس<select required value={form.instructorId} onChange={e=>chooseInstructor(e.target.value)}><option value="">اختر المدرس</option>{instructors.map(p=><option key={p.id} value={p.id}>{instructorLabel(p)}</option>)}</select></label>}
 <label>الاسم الكامل<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>اسم المستخدم (حروف إنجليزية وأرقام)<input required pattern="[a-z0-9_.-]{3,40}" dir="ltr" autoComplete="off" value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>{form.id?'كلمة مرور جديدة (اختياري)':'كلمة المرور'}<input required={!form.id} type="password" minLength={6} maxLength={128} autoComplete="new-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>
 {['delegate','deputy'].includes(form.role)&&<><label>التخصص<select value={form.department} onChange={e=>setForm({...form,department:e.target.value})}>{departments.map(d=><option key={d}>{d}</option>)}</select></label><label>المستوى<select value={form.level} onChange={e=>setForm({...form,level:Number(e.target.value)})}>{[1,2,3,4,5].map(n=><option key={n} value={n}>المستوى {n}</option>)}</select></label><label className="editPermission"><input type="checkbox" checked={!!form.canEdit} onChange={e=>setForm({...form,canEdit:e.target.checked})}/> السماح بتعديل الجدول الأسبوعي ضمن نطاقه</label></>}
 {form.role==='admin'&&<p className="accountWide">المدير يدير الجداول والمدرسين والمناديب في جميع الأقسام والمستويات. إدارة المديرين محفوظة للحساب الرئيسي.</p>}
 {form.role==='teacher'&&<fieldset className="courseAssignments accountWide"><legend>مقررات المدرس</legend><p>{form.entryIds.length} موعد أسبوعي محدد. اختر المقرر والقسم والمستوى المقصود؛ يشمل الاختيار جميع مواعيد هذه المجموعة. أي موعد جديد يُضاف لاحقًا يحتاج إلى إسناد من هنا.</p><input aria-label="بحث في المقررات" value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث بالمقرر أو القسم أو المدرس"/><div className="courseChoices">{groups.filter(g=>[g.course,g.department,g.instructor,String(g.level)].join(' ').toLowerCase().includes(query.toLowerCase())).map(g=>{const ids=g.entries.map(e=>e.id),selected=ids.filter(id=>form.entryIds.includes(id)).length;return <label className="courseChoice" key={g.key}><input type="checkbox" checked={selected===ids.length} ref={el=>{if(el)el.indeterminate=selected>0&&selected<ids.length}} onChange={e=>toggleGroup(ids,e.target.checked)}/><span><strong>{g.course}</strong><small>{g.department} · المستوى {g.level} · {g.instructor} · {ids.length} موعد</small></span></label>})}</div></fieldset>}
 <button className="primary" disabled={busy||form.role==='teacher'&&!form.entryIds.length}>{form.id?'حفظ التعديلات':'إنشاء الحساب'}</button>{form.id&&<button type="button" onClick={()=>setForm(empty)}>إلغاء التعديل</button>}</form>
 {data.members.map(m=><div className="member" key={m.id}><div><strong>{m.name}</strong><small>{m.username} · {m.id==='owner'?'الحساب الرئيسي':roleName(m.role)}{['delegate','deputy'].includes(m.role)?` · ${m.department} · المستوى ${m.level}`:m.role==='teacher'?` · ${m.entryIds.length} موعد`:''} · {m.active?'نشط':'معطّل'}</small></div>{m.id!=='owner'&&(m.role!=='admin'||data.isOwner)&&<div className="memberActions"><button disabled={busy} onClick={()=>{setQuery('');setForm({...empty,...m,instructorId:m.instructorId||'',entryIds:m.entryIds||[],canEdit:!!m.canEdit,password:''});navigateTo(accountForm)}}>تعديل</button><button disabled={busy||m.id===data.id} onClick={()=>send({action:'status',id:m.id,active:!m.active})}>{m.active?'تعطيل':'تفعيل'}</button></div>}</div>)}</section></>}
 {message&&<p role="status">{message}</p>}</div>
}
