'use client';
import {useEffect,useState} from 'react';
import type {Entry} from '../data';
type Event={id:string;action:string;actor_name:string;actor_username:string;occurred_at:string;occurrence_date:string|null;entry_json:string;before_json:string;after_json:string};
const labels:Record<string,string>={cancel:'إلغاء المحاضرة',restore:'استعادة المحاضرة',location:'تغيير المكان',restoreLocation:'استعادة المكان',edit:'تعديل الموعد',create:'إضافة موعد',delete:'حذف الموعد'};
const time=(s:string)=>new Intl.DateTimeFormat('ar-YE',{timeZone:'Asia/Aden',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(s));
const fields:Record<string,string>={course:'المقرر',instructor:'المدرس',room:'المكان',department:'التخصص',level:'المستوى',start:'البداية',end:'النهاية',groupName:'المجموعة',kind:'النوع',reason:'السبب',cancelled:'ملغية',cancelled_by:'من ألغى',created_at:'وقت الإلغاء',changed_by:'من غيّر',date:'تاريخ المحاضرة'};
function Details({value}:{value:string}){const parsed=JSON.parse(value);const records=Array.isArray(parsed)?parsed:[parsed];return <>{records.map((row,i)=>row&&<dl key={i}>{Object.entries(row).filter(([key])=>fields[key]).map(([key,v])=><div key={key}><dt>{fields[key]}</dt><dd>{typeof v==='boolean'?(v?'نعم':'لا'):key==='created_at'?time(String(v)):String(v??'')}</dd></div>)}</dl>)}</>}
export function AuditReport({start,count,department,level,revision}:{start:string;count:number;department:string;level:string;revision:unknown}){
 const [events,setEvents]=useState<Event[]>([]),[next,setNext]=useState<number|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const query=new URLSearchParams({start,days:String(count),department,level}).toString();
 useEffect(()=>{const controller=new AbortController();fetch('/api/history?'+query,{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json() as {events:Event[];nextOffset:number|null;error?:string};if(!r.ok)throw Error(d.error);setEvents(d.events);setNext(d.nextOffset);setError('')}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[query,revision]);
 const more=async()=>{setBusy(true);try{const r=await fetch('/api/history?'+query+'&offset='+next,{cache:'no-store'});const d=await r.json() as {events:Event[];nextOffset:number|null;error?:string};if(!r.ok)throw Error(d.error);setEvents(v=>[...v,...d.events]);setNext(d.nextOffset);setError('')}catch(e){setError(e instanceof Error?e.message:'تعذر التحميل')}finally{setBusy(false)}};
 return <section className="auditReport"><h3>سجل العمليات</h3><p>حسب وقت تنفيذ العملية بتوقيت عدن (UTC+3)، ضمن الفترة والقسم والمستوى المحددة أعلاه. يحتفظ السجل بالإلغاء والاستعادة والتعديلات حتى بعد عكسها. المالك يرى الجميع، والمندوب يرى نطاقه فقط. يبدأ التسجيل من تفعيل هذه الميزة.</p>{error?<p role="alert" className="failure">{error}</p>:events.length?<div className="reportTable" tabIndex={0} role="region" aria-label="سجل عمليات المحاضرات"><table><thead><tr>{['العملية','من نفّذ','تاريخ ووقت التنفيذ','المحاضرة','موعد المحاضرة','التفاصيل'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{events.map(event=>{const entry=JSON.parse(event.entry_json) as Entry;return <tr key={event.id}><td>{labels[event.action]||event.action}</td><td>{event.actor_name}<small>{event.actor_username}</small></td><td><time dateTime={event.occurred_at}>{time(event.occurred_at)}</time></td><td>{entry.course}<small>{entry.department} · المستوى {entry.level} · {entry.groupName}</small></td><td>{event.occurrence_date||'الجدول الأسبوعي'}<small dir="ltr">{entry.start}–{entry.end}</small></td><td><details><summary>قبل العملية وبعدها</summary><h4>قبل</h4><Details value={event.before_json}/><h4>بعد</h4><Details value={event.after_json}/><p>المدرس: {entry.instructor} · المكان: {entry.room}</p></details></td></tr>})}</tbody></table></div>:<p>لا توجد عمليات مسجلة ضمن هذه الفترة.</p>}{!error&&next!==null&&<button disabled={busy} onClick={more}>{busy?'جارٍ التحميل…':'عرض المزيد من العمليات'}</button>}</section>
}
