'use client';
import {useCallback,useEffect,useState} from 'react';
import {Bell} from 'lucide-react';
import {Button} from '@/components/ui/button';
import type {Entry} from '../data';
type Notice={id:string;action:'cancel'|'restore';entryId:string;date:string;actorName:string;entry:Entry;reason:string;createdAt:string;readAt:string|null};
export function NotificationsPanel({onDateChange}:{onDateChange:(date:string)=>void}){
 const [notifications,setNotifications]=useState<Notice[]>([]),[unread,setUnread]=useState(0),[next,setNext]=useState<number|null>(null),[opened,setOpened]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const load=useCallback(async(offset=0)=>{try{const r=await fetch(`/api/notifications?offset=${offset}`,{cache:'no-store'});const d=await r.json() as {error?:string;notifications:Notice[];unread:number;nextOffset:number|null};if(!r.ok)throw Error(d.error||'تعذر تحميل الإشعارات');setNotifications(old=>offset?[...old,...d.notifications.filter(n=>!old.some(x=>x.id===n.id))]:d.notifications);setUnread(d.unread);setNext(d.nextOffset);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const refresh=()=>{if(document.visibilityState==='visible')void load()};const interval=setInterval(refresh,60000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);return()=>{clearInterval(interval);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh)}},[load]);
 const read=async(id?:string)=>{setBusy(true);try{const r=await fetch('/api/notifications',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:id?'read':'readAll',id})});const d=await r.json() as {error?:string};if(!r.ok)throw Error(d.error||'تعذر تحديث الإشعار');await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <section className="notificationsPanel" id="notifications" aria-label="إشعارات المندوب"><div className="notificationsHeading"><button className="notificationsToggle" aria-expanded={opened} aria-controls="notification-list" onClick={()=>{setOpened(!opened);if(!opened)void load()}}><Bell size={20}/><strong>إشعارات المحاضرات</strong>{unread>0&&<span className="notificationBadge">{unread} غير مقروء</span>}</button><button disabled={busy} onClick={()=>load()}>تحديث</button></div>{error&&<p role="alert" className="failure">{error}</p>}{opened&&<div id="notification-list">{loading?<p role="status">جارٍ تحميل الإشعارات…</p>:<>{unread>0&&<Button variant="outline" disabled={busy} onClick={()=>read()}>تعليم الكل كمقروء</Button>}{notifications.length?notifications.map(n=><article key={n.id} className={`notificationCard ${n.readAt?'':'unread'}`}><div className="notificationCardHeading"><h3>{n.action==='cancel'?'إلغاء محاضرة':'استعادة محاضرة'}: {n.entry.course}</h3>{!n.readAt&&<span>جديد</span>}</div><p>{n.actorName} {n.action==='cancel'?'ألغى المحاضرة':'استعاد المحاضرة'}.</p><p>{n.entry.department} · المستوى {n.entry.level} · {n.date} · <span dir="ltr">{n.entry.start}–{n.entry.end}</span> · {n.entry.room}</p>{n.reason&&<p>السبب: {n.reason}</p>}<small>وقت الإشعار: {new Intl.DateTimeFormat('ar-YE',{timeZone:'Asia/Aden',dateStyle:'short',timeStyle:'short'}).format(new Date(n.createdAt))}</small><div className="notificationActions"><button onClick={()=>{onDateChange(n.date);document.getElementById('schedule')?.scrollIntoView({behavior:'smooth',block:'start'})}}>عرض جدول هذا اليوم</button>{!n.readAt&&<button disabled={busy} onClick={()=>read(n.id)}>تعليم كمقروء</button>}</div></article>):<p>لا توجد إشعارات. ستظهر هنا إلغاءات المدرسين لمحاضرات قسمك ومستواك.</p>}{next!==null&&<Button variant="outline" disabled={busy} onClick={()=>load(next)}>إشعارات أقدم</Button>}</>}</div>}</section>
}
