'use client';
import type {SchedulePayload} from '../lib/payload';
import {useMemo,useState} from 'react';
import {Dialog,DialogContent,DialogHeader,DialogTitle} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {days,type Entry} from '../data';
import type {CancelSelection} from '../lib/cancellation-selection';
type Row={entry:Entry;date:string;cancelled:boolean};
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Aden',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export function TeachingPanel({data,refresh}:{data:SchedulePayload;refresh:()=>Promise<void>}){
 const mine:Entry[]=useMemo(()=>data.entries.filter((e:Entry)=>(data.assignedEntryIds||[]).includes(e.id)),[data.entries,data.assignedEntryIds]);
 const [selection,setSelection]=useState<CancelSelection>({date:today(),period:'day',department:'',course:''}),[reason,setReason]=useState(''),[rows,setRows]=useState<Row[]|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const request=async(action:string)=>{setBusy(true);setError('');try{const r=await fetch('/api/schedule',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,selection,reason})});const body=await r.json() as {error?:string;rows?:Row[];changed?:number};if(!r.ok)throw Error(body.error||'تعذر تنفيذ العملية');if(action==='previewCancel')setRows(body.rows||[]);else{await refresh();setRows(null);setMessage(`${action==='cancelBatch'?'تم إلغاء':'تمت استعادة'} ${body.changed} محاضرة في الفترة المحددة.`)} }catch(e){setError((e as Error).message)}finally{setBusy(false)}};
 return <section className="teachingPanel" id="my-lectures"><div className="adminHeading"><div><h2>محاضراتي</h2><p>{data.name} · {mine.length} موعد أسبوعي مخصص لك</p></div></div>
 {!mine.length?<p>لم تُسند لك محاضرات بعد. يحدد المدير المقررات من بيانات حسابك.</p>:<><div className="teachingControls"><label>التاريخ داخل الأسبوع المطلوب<input type="date" required value={selection.date} onChange={e=>setSelection({...selection,date:e.target.value})}/></label><label>الفترة<select value={selection.period} onChange={e=>setSelection({...selection,period:e.target.value as 'day'|'week'})}><option value="day">اليوم المحدد</option><option value="week">الأسبوع الذي يتضمن هذا التاريخ</option></select></label><label>القسم<select value={selection.department} onChange={e=>setSelection({...selection,department:e.target.value})}><option value="">جميع الأقسام المخصصة لي</option>{[...new Set(mine.map(e=>e.department))].sort().map(d=><option key={d}>{d}</option>)}</select></label><label>المقرر<select value={selection.course} onChange={e=>setSelection({...selection,course:e.target.value})}><option value="">جميع مقرراتي</option>{[...new Set(mine.map(e=>e.course))].sort().map(c=><option key={c}>{c}</option>)}</select></label><label className="accountWide">سبب الإلغاء (اختياري)<input maxLength={250} value={reason} onChange={e=>setReason(e.target.value)}/></label></div><p>الأسبوع من السبت إلى الجمعة. الإلغاء يخص هذه الفترة فقط؛ تبقى محاضرات الأسبوع التالي قائمة.</p><Button disabled={busy||!selection.date} onClick={()=>request('previewCancel')}>معاينة المحاضرات المتأثرة</Button><details className="teacherRegistry"><summary>الجدول الأسبوعي المخصص لي</summary>{mine.slice().sort((a,b)=>((a.day+1)%7)-((b.day+1)%7)||a.start.localeCompare(b.start)).map(e=><div className="member" key={e.id}><strong>{e.course}</strong><small>{e.department} · المستوى {e.level} · {days[e.day]} · <span dir="ltr">{e.start}–{e.end}</span> · {e.room}</small></div>)}</details></>}
 {error&&<p className="failure" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <Dialog open={rows!==null} onOpenChange={open=>{if(!open&&!busy)setRows(null)}}><DialogContent className="editor batchPreview" dir="rtl"><DialogHeader><DialogTitle>تأكيد إدارة الإلغاء</DialogTitle></DialogHeader>{rows&&<><p>{rows.length} محاضرة · {rows.filter(r=>!r.cancelled).length} قائمة · {rows.filter(r=>r.cancelled).length} ملغية</p><div className="previewRows">{rows.map(({entry:e,date,cancelled})=><div className="member" key={e.id+date}><div><strong>{e.course}</strong><small>{e.department} · المستوى {e.level} · {date} · <span dir="ltr">{e.start}–{e.end}</span> · {cancelled?'ملغية':'قائمة'}</small></div></div>)}</div>{error&&<p role="alert" className="failure">{error}</p>}<Button disabled={busy||rows.every(r=>r.cancelled)} onClick={()=>request('cancelBatch')}>تأكيد إلغاء {rows.filter(r=>!r.cancelled).length} محاضرة</Button><Button variant="outline" disabled={busy||rows.every(r=>!r.cancelled)} onClick={()=>request('restoreBatch')}>استعادة {rows.filter(r=>r.cancelled).length} محاضرة ملغية</Button></>}</DialogContent></Dialog>
 </section>
}
